# Generated by Django 4.1 on 2022-08-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ban',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
