# Generated by Django 4.1 on 2022-08-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_profile_alter_comment_user_alter_video_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
