# Generated by Django 4.1 on 2022-08-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_profile_is_ban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_ban',
            new_name='is_banned',
        ),
    ]
