# Generated by Django 4.1 on 2022-08-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_rename_is_ban_profile_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
