# Generated by Django 4.0.3 on 2022-09-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_video_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
