# Generated by Django 4.0.3 on 2022-09-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='name',
            new_name='client_name',
        ),
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
