# Generated by Django 4.0.3 on 2022-09-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_rename_name_email_client_name_email_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='date',
        ),
    ]
