# Generated by Django 4.1.1 on 2022-11-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_alter_video_preview_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
