# Generated by Django 4.1.1 on 2022-11-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_alter_video_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(blank=True, default='', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
